### ISSUE TITLE
Feature: Implement Google Authentication for User Login

### ISSUE THREAD

**Issue by KingsCreatives** [KingsCreatives/Zetic#2]
# Feature: Implement Google Authentication for User Login

**Description:**

**Issue:**
Establish a secure and user-friendly authentication system. Implementing Google Authentication will streamline the sign-up and login process for our users, enhancing convenience and security.

**Objective:**
The primary objective of this feature is to integrate Google Authentication into Zetic, allowing users to sign in using their Google accounts. This implementation will eliminate the need for users to create and manage separate login credentials for our platform.

**Key Features:**
1. **Google Sign-In:** Enable users to sign in to our fitness tracker using their Google accounts with a single click.
2. **Secure Authentication:** Implement OAuth 2.0 protocol for secure authentication, ensuring user data privacy and protection.
3. **User Profile Sync:** Upon successful authentication, sync relevant user profile information from Google accounts to our application.
4. **Error Handling:** Implement robust error handling mechanisms to manage authentication failures gracefully and provide informative error messages to users.
5. **Testing:** Conduct comprehensive testing across various devices and platforms to ensure seamless integration and functionality.

**Implementation Details:**
- Utilize Google Sign-In API to implement authentication functionality.
- Integrate necessary dependencies and libraries for OAuth 2.0 authentication.
- Configure callback URLs and authentication scopes according to our application requirements.
- Implement user profile synchronization to fetch and store relevant user data from Google accounts securely.

**Comment by FinzyPHINZY** [comment]
I will get to work on this! I will be done this time tomorrow

**Comment by KingsCreatives** [comment]
That will be nice

**Comment by KingsCreatives** [comment]
I want to take inspiration from this design on Dribble, in terms of color and feel from this l [link](https://dribbble.com/shots/20165428-Activity-Tracker-App?utm_source=Clipboard_Shot&utm_campaign=MindInventoryUIUX&utm_content=Activity%20Tracker%20App&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=MindInventoryUIUX&utm_content=Activity%20Tracker%20App&utm_medium=Social_Share)

**Comment by FinzyPHINZY** [comment]
> I want to take inspiration from this design on Dribble, in terms of color and feel from this [link](https://dribbble.com/shots/20165428-Activity-Tracker-App?utm_source=Clipboard_Shot&utm_campaign=MindInventoryUIUX&utm_content=Activity%20Tracker%20App&utm_medium=Social_Share&utm_source=Clipboard_Shot&utm_campaign=MindInventoryUIUX&utm_content=Activity%20Tracker%20App&utm_medium=Social_Share)

This is great! We can do that
